import { fileURLToPath } from "node:url";
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import { importX } from "eslint-plugin-import-x";
import { createTypeScriptImportResolver } from "eslint-import-resolver-typescript";

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    plugins: {
      "react-hooks": reactHooks,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // `src/types/generated/` is ts-rs output committed verbatim (audit DUP-030);
    // it is not written in the repo's lint/format style and is regenerated by
    // `cargo test`, so linting it would fight the generator.
    ignores: ["dist/", "src-tauri/", "coverage/", "src/types/generated/"],
  },
  {
    // Production frontend code: enforce the logging policy from .claude/CLAUDE.md —
    // debug output must go through `frontendLog` (→ LogViewer), never `console.*`,
    // which is invisible to users. This ratchet stops a new console.* silently
    // regressing after the WA-FE-006 migration removed the existing ones.
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      "no-console": "error",
      // Silent-catch policy (#4333): an empty `catch {}` hides a failure from the
      // user and the Log Viewer. Log it (frontendLog / fireAndForget), surface it
      // (toast), or rethrow; a deliberately ignored error carries a comment saying why.
      "no-empty": ["error", { allowEmptyCatch: false }],
    },
  },
  {
    // Caught-error rendering policy (#4104). Tauri rejects a command error as a
    // structured `{ code, message }` envelope, not an `Error`, so `String(err)`
    // (or a bare `${err}` interpolation) renders it as "[object Object]" and hides the real failure. Use
    // `errorMessage()` from `@/utils/errorMessage` instead, which surfaces the
    // envelope's `message`. The helper itself is the one legitimate fallback.
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/utils/errorMessage.ts", "src/**/*.test.{ts,tsx}", "src/test/**"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.name='String'][arguments.length=1][arguments.0.name=/^(e|err|error|ex|exc)$/]",
          message:
            'Use errorMessage(err) from @/utils/errorMessage — String() of a structured IPC error renders "[object Object]" (#4104).',
        },
        {
          // `${err}` has the same "[object Object]" failure as String(err).
          selector: "TemplateLiteral > Identifier[name=/^(e|err|error|ex|exc)$/]",
          message:
            'Interpolate errorMessage(err) from @/utils/errorMessage — "${err}" of a structured IPC error renders "[object Object]" (#4104).',
        },
        {
          // Silent-catch policy (#4333): `.catch(() => {})` swallows a rejection
          // with no trace. A comment-only body counts as empty too.
          selector:
            "CallExpression[callee.property.name='catch'] > :matches(ArrowFunctionExpression, FunctionExpression)[body.type='BlockStatement'][body.body.length=0]",
          message:
            'Do not swallow a rejection silently (#4333). Use fireAndForget(p, "<reason>") for best-effort work, or log/toast the error in the handler.',
        },
      ],
    },
  },
  {
    // Native file dialogs go through `@/services/nativeDialog` (#4122), the seam
    // where the test-bridge harness pre-programs a dialog's result. A direct
    // plugin import would bypass it and bring back an operator-only dialog in
    // the system tests. The wrapper itself is the one legitimate importer.
    // The fs / opener plugins are limited to what the capability grants (#3115).
    files: ["src/**/*.{ts,tsx}"],
    ignores: [
      "src/services/nativeDialog.ts",
      "src/components/ui/Toast/**",
      "src/**/*.test.{ts,tsx}",
      "src/test/**",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            // ui/Toast is the app's toast policy (errors persist until dismissed);
            // a direct sonner import bypasses it (#4333). The wrapper is exempt.
            {
              name: "sonner",
              message:
                'Use toast from "@/components/ui" — it applies the persist-errors policy (#4333).',
            },
            {
              name: "@tauri-apps/plugin-dialog",
              importNames: ["open", "save"],
              message:
                "Import open/save from @/services/nativeDialog so the test bridge can stub the dialog (#4122).",
            },
            // The capability grants the webview only the fs plugin's text
            // read/write — on dialog-picked paths — and no path opener (#3115).
            // Anything else would fail at runtime; local files go through the
            // backend's validated commands in @/services/api instead.
            {
              name: "@tauri-apps/plugin-fs",
              allowImportNames: ["readTextFile", "writeTextFile"],
              message:
                "Only readTextFile/writeTextFile on a native-dialog pick are granted (#3115); use the local_* commands in @/services/api.",
            },
            {
              name: "@tauri-apps/plugin-opener",
              allowImportNames: ["openUrl"],
              message:
                "Only openUrl (http/https/mailto) is granted (#3115); open a folder with localOpenFolder from @/services/api.",
            },
          ],
        },
      ],
    },
  },
  {
    // Import-cycle detection (audit TOOL-014). A cycle makes module init order
    // depend on which file is imported first, which surfaces as `undefined`
    // bindings at startup. Only `no-cycle` is enabled — the rest of the
    // import-x ruleset is out of scope here. The TS resolver understands the
    // `@/*` path alias and `.ts`/`.tsx` extensions (see tsconfig.eslint.json for
    // why it does not point at tsconfig.json directly). `import type` edges are
    // erased at compile time, so import-x ignores them: only runtime cycles count.
    files: ["src/**/*.{ts,tsx}"],
    plugins: {
      "import-x": importX,
    },
    settings: {
      // Parser/extension settings from the plugin's TS preset: without them
      // import-x only follows `.js` files, so every `.ts`/`.tsx` edge is
      // dropped and no cycle is ever reported.
      "import-x/extensions": importX.flatConfigs.typescript.settings["import-x/extensions"],
      "import-x/parsers": importX.flatConfigs.typescript.settings["import-x/parsers"],
      "import-x/resolver-next": [
        createTypeScriptImportResolver({
          project: fileURLToPath(new URL("./tsconfig.eslint.json", import.meta.url)),
        }),
      ],
    },
    rules: {
      "import-x/no-cycle": ["error", { ignoreExternal: true }],
    },
  },
  {
    // Clipboard policy (#4327, LIBFE2-004): navigator.clipboard rejects on
    // macOS/WKWebView when the window is not focused and silently drops the copy.
    // Use the Tauri clipboard plugin, which every copy action in the app shares.
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/**/*.test.{ts,tsx}", "src/test/**"],
    rules: {
      "no-restricted-properties": [
        "error",
        {
          object: "navigator",
          property: "clipboard",
          message:
            'Use readText/writeText from "@tauri-apps/plugin-clipboard-manager" — navigator.clipboard fails in an unfocused WKWebView (#4327).',
        },
      ],
    },
  },
  {
    // Tests, test harnesses, and the vitest setup are dev-only code that never
    // ships to users, so console.* is fine there — turn the ratchet back off.
    files: ["src/**/*.test.{ts,tsx}", "src/test/**"],
    rules: {
      "no-console": "off",
    },
  }
);
