pub mod about;
pub mod agent;
pub mod connection;
pub mod connection_path;
pub mod credential;
pub mod credential_vault;
pub mod embedded_servers;
pub mod files;
pub mod inventory_import;
pub mod local_process;
pub mod logs;
pub mod macros;
pub mod network;
pub mod plugin;
pub mod plugin_update;
pub mod portable;
pub mod projection;
// Test-bridge-only diagnostic projection region (#2164). Gated (SEC-005) so it
// is compiled out of release builds along with the rest of the test bridge.
#[cfg(feature = "test-bridge")]
pub mod projection_diag;
pub mod remote_desktop;
pub mod remote_desktop_image;
pub mod restore_mode;
pub mod session;
pub mod session_history;
pub mod shell_integration;
pub mod spawn;
pub mod ssh_config_import;
pub mod ssh_host_key;
pub mod transfer;
pub mod tunnel;
pub mod update;
pub mod window;
pub mod workflows;
pub mod workspace;
pub mod xserver;
