"""termiHub Python system-test harness.

Drives the real built app over the cross-platform WebSocket bridge and owns the
lifecycle of the app and agent processes — the foundation for system/resilience
tests that run identically on Linux, Windows, and macOS (issue #802).
"""

from .bridge import Bridge, BridgeError, Driver
from .fixtures import (
    SSH_BANNER_PORT,
    SSH_BANNER_SERVICE,
    SSH_HOST,
    SSH_KEY_PATH,
    SSH_KEYS_PORT,
    SSH_KEYS_SERVICE,
    SSH_PASSWORD,
    SSH_PASSWORD_PORT,
    SSH_PASSWORD_SERVICE,
    SSH_TUNNEL_PORT,
    SSH_TUNNEL_SERVICE,
    SSH_USERNAME,
    TELNET_HOST,
    TELNET_PORT,
    TELNET_SERVICE,
    ComposeFixture,
    ContainerRuntimeUnavailable,
    container_runtime,
    wait_for_port,
)
from .orchestrator import AgentInstance, AppInstance, agent_binary_path, app_binary_path
from .systemtest import SystemTest, unique_name
from .ui import (
    ConnectionsUi,
    LayoutUi,
    MonitoringUi,
    PasswordPromptUi,
    SettingsUi,
    SftpUi,
    SidebarUi,
    SshUi,
    TabsUi,
    TerminalUi,
    connection_item_testid,
    connections,
    find_connection,
    find_folder,
    folder_toggle_testid,
    folders,
)

__all__ = [
    "Bridge",
    "BridgeError",
    "Driver",
    "AppInstance",
    "AgentInstance",
    "app_binary_path",
    "agent_binary_path",
    "SystemTest",
    "ConnectionsUi",
    "TerminalUi",
    "TabsUi",
    "LayoutUi",
    "SidebarUi",
    "PasswordPromptUi",
    "SshUi",
    "MonitoringUi",
    "SftpUi",
    "SettingsUi",
    "connections",
    "find_connection",
    "folders",
    "find_folder",
    "connection_item_testid",
    "folder_toggle_testid",
    "unique_name",
    "ComposeFixture",
    "ContainerRuntimeUnavailable",
    "container_runtime",
    "wait_for_port",
    "SSH_HOST",
    "SSH_PASSWORD_SERVICE",
    "SSH_PASSWORD_PORT",
    "SSH_KEYS_SERVICE",
    "SSH_KEYS_PORT",
    "SSH_BANNER_SERVICE",
    "SSH_BANNER_PORT",
    "SSH_TUNNEL_SERVICE",
    "SSH_TUNNEL_PORT",
    "SSH_USERNAME",
    "SSH_PASSWORD",
    "SSH_KEY_PATH",
    "TELNET_HOST",
    "TELNET_SERVICE",
    "TELNET_PORT",
]
