"""termiHub Python system-test harness.

Drives the real built app over the cross-platform WebSocket bridge and owns the
lifecycle of the app and agent processes — the foundation for system/resilience
tests that run identically on Linux, Windows, and macOS (issue #802).
"""

from .bridge import Bridge, BridgeError, Driver, screenshot_to_png_bytes
from .fixtures import (
    REMOTE_AGENT_PENDING_PORT,
    REMOTE_AGENT_PENDING_SERVICE,
    REMOTE_AGENT_PENDING_VERSION,
    REMOTE_AGENT_PORT,
    REMOTE_AGENT_SERVICE,
    SSH_BANNER_PORT,
    SSH_BANNER_SERVICE,
    SSH_HOST,
    SSH_KEY_PASSPHRASE,
    SSH_KEY_PASSPHRASE_PATH,
    SSH_KEY_PATH,
    SSH_KEYS_PORT,
    SSH_KEYS_SERVICE,
    SSH_PASSWORD,
    SSH_PASSWORD_PORT,
    SSH_PASSWORD_SERVICE,
    SSH_TUNNEL_PORT,
    SSH_TUNNEL_SERVICE,
    SSH_USERNAME,
    SSH_X11_PORT,
    SSH_X11_SERVICE,
    TELNET_HOST,
    TELNET_PORT,
    TELNET_SERVICE,
    ComposeFixture,
    ContainerRuntimeUnavailable,
    SshServerControl,
    container_runtime,
    stage_remote_agent_binary,
    wait_for_port,
)
from .manual import (
    ManualPrompter,
    ManualRecord,
    ManualResult,
    ManualSession,
    build_manual_report,
    manual_skip_reason,
    write_manual_report,
)
from .clipboard import read_os_clipboard
from .display import ensure_local_display
from .orchestrator import AgentInstance, AppInstance, agent_binary_path, app_binary_path
from .projection import ProjectionHarness
from .ssh_agent import agent_has_key, key_fingerprint, sha256_fingerprints
from .systemtest import SystemTest, unique_name
from .transfers import TftpUnavailable, ftp_download, ftp_list, tftp_download
from .ui import (
    AgentUi,
    ConfigRecoveryUi,
    ConnectionsUi,
    CredentialStoreUi,
    EditorUi,
    EmbeddedServicesUi,
    FilesUi,
    LayoutUi,
    ManualUi,
    MonitoringUi,
    NetworkToolsUi,
    PasswordPromptUi,
    SettingsUi,
    ShellFsUi,
    SftpUi,
    SidebarUi,
    SshUi,
    TabsUi,
    TerminalUi,
    WorkflowUi,
    connection_item_testid,
    connections,
    file_row_testid,
    find_connection,
    find_folder,
    folder_toggle_testid,
    folders,
)

__all__ = [
    "Bridge",
    "BridgeError",
    "Driver",
    "screenshot_to_png_bytes",
    "AppInstance",
    "AgentInstance",
    "app_binary_path",
    "agent_binary_path",
    "SystemTest",
    "ProjectionHarness",
    "AgentUi",
    "ConfigRecoveryUi",
    "ConnectionsUi",
    "CredentialStoreUi",
    "TerminalUi",
    "TabsUi",
    "LayoutUi",
    "SidebarUi",
    "PasswordPromptUi",
    "SshUi",
    "MonitoringUi",
    "SftpUi",
    "FilesUi",
    "EditorUi",
    "EmbeddedServicesUi",
    "SettingsUi",
    "ManualUi",
    "NetworkToolsUi",
    "WorkflowUi",
    "ManualPrompter",
    "ManualResult",
    "ManualRecord",
    "ManualSession",
    "manual_skip_reason",
    "build_manual_report",
    "write_manual_report",
    "ShellFsUi",
    "connections",
    "find_connection",
    "folders",
    "find_folder",
    "connection_item_testid",
    "folder_toggle_testid",
    "file_row_testid",
    "unique_name",
    "ComposeFixture",
    "ContainerRuntimeUnavailable",
    "SshServerControl",
    "container_runtime",
    "stage_remote_agent_binary",
    "wait_for_port",
    "REMOTE_AGENT_SERVICE",
    "REMOTE_AGENT_PORT",
    "REMOTE_AGENT_PENDING_SERVICE",
    "REMOTE_AGENT_PENDING_PORT",
    "REMOTE_AGENT_PENDING_VERSION",
    "SSH_HOST",
    "SSH_PASSWORD_SERVICE",
    "SSH_PASSWORD_PORT",
    "SSH_KEYS_SERVICE",
    "SSH_KEYS_PORT",
    "SSH_BANNER_SERVICE",
    "SSH_BANNER_PORT",
    "SSH_TUNNEL_SERVICE",
    "SSH_TUNNEL_PORT",
    "SSH_X11_SERVICE",
    "SSH_X11_PORT",
    "SSH_USERNAME",
    "SSH_PASSWORD",
    "SSH_KEY_PATH",
    "TELNET_HOST",
    "TELNET_SERVICE",
    "TELNET_PORT",
    "SSH_KEY_PASSPHRASE",
    "SSH_KEY_PASSPHRASE_PATH",
    "ftp_download",
    "ftp_list",
    "tftp_download",
    "TftpUnavailable",
    "agent_has_key",
    "key_fingerprint",
    "sha256_fingerprints",
    "ensure_local_display",
    "read_os_clipboard",
]
