@echo off
REM Regenerate docs\concepts\mockups-index.html — a single browsable page linking
REM every concept mockup. Windows counterpart of build-mockups-index.sh.
REM Part of the AI-driven concept workflow. Runnable from anywhere in the repo.

setlocal enabledelayedexpansion

REM Resolve repo root relative to this script (scripts\internal\ -> repo root).
set "SCRIPT_DIR=%~dp0"
pushd "%SCRIPT_DIR%..\.." || exit /b 1
set "REPO_ROOT=%CD%"
popd
set "CONCEPTS_DIR=%REPO_ROOT%\docs\concepts"
set "OUT=%CONCEPTS_DIR%\mockups-index.html"

pushd "%CONCEPTS_DIR%" || exit /b 1

> "%OUT%" (
  echo ^<!doctype html^>
  echo ^<!-- GENERATED by scripts\internal\build-mockups-index.cmd — do not edit by hand. --^>
  echo ^<html lang="en"^>
  echo   ^<head^>
  echo     ^<meta charset="utf-8" /^>
  echo     ^<meta name="viewport" content="width=device-width, initial-scale=1" /^>
  echo     ^<title^>termiHub Concept Mockups^</title^>
  echo     ^<link rel="stylesheet" href="_assets/mockup.css" /^>
  echo     ^<style^>
  echo       .idx-group { margin: 0 0 22px; }
  echo       .idx-group h2 { font-size: 14px; margin: 0 0 6px; }
  echo       .idx-group ul { margin: 0; padding-left: 18px; }
  echo       .idx-group a { color: var^(--text-accent^); text-decoration: none; }
  echo     ^</style^>
  echo   ^</head^>
  echo   ^<body class="mockup-doc"^>
  echo     ^<h1^>termiHub Concept Mockups^</h1^>
  echo     ^<p class="mockup-meta"^>Hand-written, layout-altitude mockups across all concepts.^</p^>
)

set "CURRENT="
for /f "delims=" %%F in ('dir /b /s /a-d "mockups\*.html" 2^>nul ^| sort') do (
  set "FULL=%%F"
  set "REL=!FULL:%CONCEPTS_DIR%\=!"
  set "REL=!REL:\=/!"
  for /f "tokens=1,* delims=/" %%a in ("!REL!") do set "REST=!REL!"
  call :emit "!REL!"
)

>> "%OUT%" (
  if defined CURRENT echo       ^</ul^>^</div^>
  echo   ^</body^>
  echo ^</html^>
)

popd
echo Wrote "%OUT%".
endlocal
goto :eof

:emit
set "REL=%~1"
for /f "delims=" %%p in ("%REL%") do set "CONCEPT=%%p"
REM concept_path = everything before /mockups/
set "CONCEPT=%REL:/mockups/="&REM %"
for /f "tokens=1 delims=|" %%x in ("%REL:/mockups/=^|%") do set "CONCEPT=%%x"
for /f "tokens=2 delims=|" %%y in ("%REL:/mockups/=^|%") do set "NAME=%%y"
if not "%CONCEPT%"=="%CURRENT%" (
  >> "%OUT%" (
    if defined CURRENT echo       ^</ul^>^</div^>
    echo       ^<div class="idx-group"^>^<h2^>^<code^>%CONCEPT%^</code^>^</h2^>^<ul^>
  )
  set "CURRENT=%CONCEPT%"
)
>> "%OUT%" echo         ^<li^>^<a href="%REL%"^>%NAME%^</a^>^</li^>
goto :eof
