#!/bin/bash
# Regenerate docs/concepts/mockups-index.html — a single browsable gallery linking
# every concept's visual surface. Part of the AI-driven concept workflow.
#
# Scans for single-file concepts (docs/concepts/<status>/<name>.html) and any
# legacy folder mockups (docs/concepts/<status>/<name>/mockups/*.html), groups by
# concept, and writes a static index. No server, no deps beyond a POSIX shell.
#
# Usage: scripts/internal/build-mockups-index.sh   (runnable from anywhere in the repo)

set -euo pipefail

# Resolve repo root relative to this script so it works from any CWD.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONCEPTS_DIR="$REPO_ROOT/docs/concepts"
OUT="$CONCEPTS_DIR/mockups-index.html"

cd "$CONCEPTS_DIR"

# Collect visual surfaces (portable — no GNU-only flags):
#   - single-file concepts:  <status>/<name>.html
#   - legacy folder mockups: <status>/<name>/mockups/*.html
# Exclude shared assets and this generated index itself. Emit "group<TAB>file"
# then sort by group so each concept's entries stay contiguous.
mockups=$(find . -type f -name '*.html' \
  ! -path './_assets/*' ! -name 'mockups-index.html' \
  | sed 's|^\./||' \
  | while IFS= read -r f; do
      # NB: avoid `case ... ;;` here — macOS bash 3.2 has a parser bug where a
      # `case` inside $(...) command substitution fails ("syntax error near `;;'").
      if [ "$f" != "${f%/mockups/*}" ]; then
        g="${f%%/mockups/*}"   # legacy folder mockup
      else
        g="$(dirname "$f")"    # single-file concept
      fi
      printf '%s\t%s\n' "$g" "$f"
    done | sort)

{
  cat <<'HTML'
<!doctype html>
<!-- GENERATED by scripts/internal/build-mockups-index.sh — do not edit by hand. -->
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>termiHub Concept Mockups</title>
    <link rel="stylesheet" href="_assets/mockup.css" />
    <style>
      .idx-group { margin: 0 0 22px; }
      .idx-group h2 { font-size: 14px; margin: 0 0 6px; }
      .idx-group h2 code { font-family: var(--mono); color: var(--text-accent); font-size: 13px; }
      .idx-group ul { margin: 0; padding-left: 18px; }
      .idx-group li { margin: 3px 0; }
      .idx-group a { color: var(--text-accent); text-decoration: none; }
      .idx-group a:hover { text-decoration: underline; }
      .idx-empty { color: var(--text-secondary); }
    </style>
  </head>
  <body class="mockup-doc">
    <h1>termiHub Concept Gallery</h1>
    <p class="mockup-meta">
      Every concept's visual surface — single-file concepts and any legacy folder mockups.
      Regenerate with <code>scripts/internal/build-mockups-index.sh</code>.
    </p>
HTML

  if [ -z "$mockups" ]; then
    echo '    <p class="idx-empty">No mockups found yet.</p>'
  else
    current_concept=""
    while IFS="$(printf '\t')" read -r concept_path file; do
      [ -n "$file" ] || continue
      case "$file" in
        */mockups/*) name="${file##*/mockups/}" ;;   # legacy: toolbar.html
        *) name="$(basename "$file")" ;;             # single-file concept
      esac
      if [ "$concept_path" != "$current_concept" ]; then
        [ -n "$current_concept" ] && echo '      </ul></div>'
        current_concept="$concept_path"
        echo '      <div class="idx-group">'
        echo "        <h2><code>$concept_path</code></h2><ul>"
      fi
      echo "        <li><a href=\"$file\">$name</a></li>"
    done <<EOF
$mockups
EOF
    echo '      </ul></div>'
  fi

  cat <<'HTML'
  </body>
</html>
HTML
} >"$OUT"

count=$(printf '%s\n' "$mockups" | grep -c . || true)
echo "Wrote $OUT ($count mockup(s))."
