import { describe, it, expect } from "vitest";
import { fileURLToPath } from "url";
import path from "path";
import {
  isPrerelease,
  parseLockfile,
  findProblems,
  loadRepo,
  ALLOWLIST_PATH,
} from "./check-prerelease-crates.mjs";

const LOCK = [
  "# This file is automatically @generated by Cargo.",
  "version = 4",
  "",
  "[[package]]",
  'name = "rsa"',
  'version = "0.10.0-rc.18"',
  'source = "registry+https://github.com/rust-lang/crates.io-index"',
  "dependencies = [",
  ' "pkcs1",',
  "]",
  "",
  "[[package]]",
  'name = "toml"',
  'version = "1.1.2+spec-1.1.0"',
  "",
  "[[package]]",
  'name = "serde"',
  'version = "1.0.228"',
  "",
].join("\n");

const entry = (name, version, extra = {}) => ({
  name,
  version,
  reason: "accepted",
  tracker: "#3734",
  ...extra,
});

describe("isPrerelease", () => {
  it("detects a semver pre-release part", () => {
    expect(isPrerelease("0.10.0-rc.18")).toBe(true);
    expect(isPrerelease("5.0.0-pre.6")).toBe(true);
    expect(isPrerelease("1.0.0-rc.1+build.5")).toBe(true);
  });

  it("ignores build metadata, even when it contains a dash", () => {
    expect(isPrerelease("1.1.2+spec-1.1.0")).toBe(false);
    expect(isPrerelease("0.4.0+wasi-0.3.0-rc-2026-01-06")).toBe(false);
    expect(isPrerelease("1.0.228")).toBe(false);
  });
});

describe("parseLockfile", () => {
  it("extracts every package name and version", () => {
    expect(parseLockfile(LOCK)).toEqual([
      { name: "rsa", version: "0.10.0-rc.18" },
      { name: "toml", version: "1.1.2+spec-1.1.0" },
      { name: "serde", version: "1.0.228" },
    ]);
  });

  it("handles CRLF line endings", () => {
    expect(parseLockfile(LOCK.replace(/\n/g, "\r\n"))).toHaveLength(3);
  });
});

describe("findProblems", () => {
  it("passes when every pre-release is allowlisted", () => {
    expect(
      findProblems({ "Cargo.lock": LOCK }, { crates: [entry("rsa", "0.10.0-rc.18")] })
    ).toEqual([]);
  });

  it("fails on an unreviewed pre-release", () => {
    const problems = findProblems({ "Cargo.lock": LOCK }, { crates: [] });
    expect(problems).toHaveLength(1);
    expect(problems[0]).toContain("rsa@0.10.0-rc.18");
  });

  it("fails when a pre-release moved to a different version", () => {
    const problems = findProblems(
      { "Cargo.lock": LOCK },
      { crates: [entry("rsa", "0.10.0-rc.17")] }
    );
    expect(problems.some((p) => p.includes("rsa@0.10.0-rc.18 is not in the reviewed set"))).toBe(
      true
    );
    expect(problems.some((p) => p.includes("rsa@0.10.0-rc.17 is no longer"))).toBe(true);
  });

  it("fails on a stale allowlist entry", () => {
    const problems = findProblems(
      { "Cargo.lock": LOCK },
      { crates: [entry("rsa", "0.10.0-rc.18"), entry("ssh-key", "0.7.0-rc.10")] }
    );
    expect(problems).toEqual([
      `${ALLOWLIST_PATH}: ssh-key@0.7.0-rc.10 is no longer in any lockfile — remove the stale entry`,
    ]);
  });

  it("checks every lockfile", () => {
    const sidecar = '[[package]]\nname = "picky"\nversion = "7.0.0-rc.25"\n';
    const problems = findProblems(
      { "Cargo.lock": LOCK, "rdp-sidecar/Cargo.lock": sidecar },
      { crates: [entry("rsa", "0.10.0-rc.18")] }
    );
    expect(problems).toHaveLength(1);
    expect(problems[0]).toMatch(/^rdp-sidecar\/Cargo\.lock: pre-release picky@7\.0\.0-rc\.25/);
  });

  it("rejects malformed entries", () => {
    const problems = findProblems(
      { "Cargo.lock": LOCK },
      {
        crates: [
          entry("rsa", "0.10.0-rc.18", { reason: "", tracker: "soon" }),
          entry("serde", "1.0.228"),
        ],
      }
    );
    expect(problems.some((p) => p.includes('needs a non-empty "reason"'))).toBe(true);
    expect(problems.some((p) => p.includes('"tracker" must be an issue reference'))).toBe(true);
    expect(problems.some((p) => p.includes("serde@1.0.228): version is not a pre-release"))).toBe(
      true
    );
  });

  it("rejects a missing or malformed allowlist", () => {
    expect(findProblems({ "Cargo.lock": LOCK }, null)).toHaveLength(1);
    expect(findProblems({ "Cargo.lock": LOCK }, { crates: "x" })).toHaveLength(1);
  });

  it("reports a missing lockfile", () => {
    expect(findProblems({ "Cargo.lock": null }, { crates: [] })).toEqual(["Cargo.lock not found"]);
  });
});

describe("the real repository", () => {
  it("locks only reviewed pre-releases", () => {
    const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
    const { lockfiles, allowlist } = loadRepo(root);
    expect(findProblems(lockfiles, allowlist)).toEqual([]);
  });
});
